name: Preact Marquee

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'

      - name: Test
        run: |
          yarn install
          yarn test:coverage
